In [2]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\python38-32\lib\site-packages (1.18.4)
Could not build wheels for numpy, since package 'wheel' is not installed.


In [3]:
import numpy as np

In [4]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [5]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [9]:
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
array_of_ones = np.ones((3,2), dtype=np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [12]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [15]:
array_of_floats = np.arange(1, 3, 0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [16]:
array_2D = np.array([(3,4,6), (2,1,6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [17]:
array_2D.shape

(2, 3)

In [18]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
x = np.arange(8)

In [23]:
print(x)

[0 1 2 3 4 5 6 7]


In [24]:
y = np.arange(16).reshape(4,4)

In [25]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
z =  np.arange(36).reshape(3,4,3)

In [27]:
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [28]:
np.arange(12100)

array([    0,     1,     2, ..., 12097, 12098, 12099])

In [29]:
print(np.arange(12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]


In [33]:
np.set_printoptions(threshold = 110)

In [32]:
print(np.arange(12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]
