In [2]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\python38-32\lib\site-packages (1.18.4)
Could not build wheels for numpy, since package 'wheel' is not installed.


In [2]:
import numpy as np

In [4]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [5]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [9]:
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
array_of_ones = np.ones((3,2), dtype=np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [12]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [15]:
array_of_floats = np.arange(1, 3, 0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [16]:
array_2D = np.array([(3,4,6), (2,1,6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [17]:
array_2D.shape

(2, 3)

In [18]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
x = np.arange(8)

In [23]:
print(x)

[0 1 2 3 4 5 6 7]


In [24]:
y = np.arange(16).reshape(4,4)

In [25]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
z =  np.arange(36).reshape(3,4,3)

In [27]:
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [28]:
np.arange(12100)

array([    0,     1,     2, ..., 12097, 12098, 12099])

In [29]:
print(np.arange(12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]


In [33]:
np.set_printoptions(threshold = 110)

In [32]:
print(np.arange(12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]


In [34]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [35]:
np.set_printoptions(threshold = 50)

In [36]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 ...
 [70 71 72 ... 77 78 79]
 [80 81 82 ... 87 88 89]
 [90 91 92 ... 97 98 99]]


In [3]:
p = np.array([9,8,7])
q = np.array([3,2,4])

In [4]:
p + q

array([12, 10, 11])

In [5]:
p - q

array([6, 6, 3])

In [6]:
p * q

array([27, 16, 28])

In [7]:
p % q

array([0, 0, 3], dtype=int32)

In [8]:
p % 2

array([1, 0, 1], dtype=int32)

In [9]:
p > 8

array([ True, False, False])

In [10]:
p < 9

array([False,  True,  True])

In [11]:
x = np.array([[2,1], [1,3]])
y = np.array([[3,2], [4,2]])
print('x: \n', x)
print('y: \n', y)

x: 
 [[2 1]
 [1 3]]
y: 
 [[3 2]
 [4 2]]


In [12]:
x + y

array([[5, 3],
       [5, 5]])

In [13]:
x - y

array([[-1, -1],
       [-3,  1]])

In [14]:
x * y

array([[6, 2],
       [4, 6]])

In [15]:
x.dot(y)

array([[10,  6],
       [15,  8]])

In [16]:
np.dot(x,y)

array([[10,  6],
       [15,  8]])

In [18]:
x *= 4
x

array([[24, 20],
       [20, 28]])

In [19]:
fleet_mileage = np.array([14130, 37234, 21892, 11479, 6890, 27981])

In [20]:
fleet_mileage.sum()

119606

In [21]:
fleet_mileage.min()

6890

In [22]:
fleet_mileage.max()

37234

In [23]:
fleet_mileage.mean()

19934.333333333332

In [24]:
num = np.arange(16).reshape(4,4)

In [25]:
num.sum()

120

In [26]:
num.sum(axis = 0)

array([24, 28, 32, 36])

In [27]:
num.sum(axis = 1)

array([ 6, 22, 38, 54])

In [28]:
num.min(axis = 1)

array([ 0,  4,  8, 12])

In [29]:
num.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])